const path = require('path');
const webpack = require('webpack');
const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');
const nodeExternals = require('webpack-node-externals');

// 基础配置
const baseConfig = {
  mode: 'production',
  target: 'node',
  node: {
    __dirname: false,
    __filename: false,
  },
  resolve: {
    extensions: ['.ts', '.js'],
    extensionAlias: {
      // 处理 TypeScript ESM 导入中的 .js 扩展名
      '.js': ['.ts', '.js'],
    },
    fallback: {
      // 在 Node.js 环境中我们不需要这些 polyfills
      "buffer": false,
      "process": false,
    }
  },
  module: {
    rules: [
      {
        test: /\.ts$/,
        use: [
          {
            loader: 'ts-loader',
            options: {
              transpileOnly: true, // 类型检查由 ForkTsCheckerWebpackPlugin 处理
              configFile: 'tsconfig.json'
            }
          }
        ],
        exclude: /node_modules/
      }
    ]
  },
  plugins: [
    new ForkTsCheckerWebpackPlugin({
      typescript: {
        configFile: path.resolve(__dirname, 'tsconfig.json'),
      }
    }),
    // 忽略有问题的 native 依赖
    new webpack.IgnorePlugin({
      resourceRegExp: /^(fsevents|@swc\/core.*)$/,
    }),
    // 定义构建时的全局变量
    new webpack.DefinePlugin({
      __MCP_VERSION__: JSON.stringify(require('./package.json').version),
    }),
  ],
  optimization: {
    minimize: true, // 启用压缩来减小文件体积
  },
  stats: {
    warnings: false, // 忽略循环依赖警告
  }
};

// 导出配置
module.exports = [
  // 库文件 - ESM 版本，打包大部分依赖
  {
    ...baseConfig,
    name: 'library-esm',
    entry: './src/index.ts',
    output: {
      path: path.resolve(__dirname, 'dist'),
      filename: 'index.js',
      library: {
        type: 'module'
      },
      chunkFormat: 'module',
      environment: {
        module: true,
        dynamicImport: true
      }
    },
    experiments: {
      outputModule: true
    },
    externalsType: 'module',
    externals: [
      nodeExternals({
        // 打包大部分第三方依赖，但排除有问题的包
        allowlist: [
          'zod',
          'punycode', 
          '@types/adm-zip',
          'adm-zip',
          'cors',
          '@modelcontextprotocol/sdk',
          /^@modelcontextprotocol\/sdk\//,
          'zod-to-json-schema',
          'ajv',
          /^ajv\//,
          // 安全的第三方依赖
          'fast-json-stable-stringify',
          'open',
          'uri-js',
          'fast-deep-equal',
          'json-schema-traverse',
          // 小型工具库
          'is-wsl',
          'define-lazy-prop',
          'default-browser',
          'is-inside-container',
          'default-browser-id',
          'bundle-name', 
          'is-docker',
          'run-applescript',
          // CloudBase 包
          '@cloudbase/manager-node',
          /^@cloudbase\//,
          // 其他可以安全打包的依赖
          'tslib',
          'buffer',
          'process',
          'util',
          'events',
          'stream',
          'string_decoder',
          'querystring',
          'timers',
          'inherits',
          'safe-buffer',
          'readable-stream',
          'url',
          'core-util-is',
          'isarray',
          'util-deprecate',
          'string_decoder',
          'process-nextick-args',
          'end-of-stream',
          'once',
          'wrappy',
          'xtend',
          'minimist',
          'path-browserify',
          'os-browserify',
          'crypto-browserify',
          'browserify-zlib',
          'https-browserify',
          'http-browserify',
          'constants-browserify',
          'assert',
          'tty-browserify',
          'vm-browserify',
          'domain-browser',
          'console-browserify',
          'querystring-es3',
          'url-parse',
          'requires-port',
          'debug',
          'ms',
          'mime-types',
          'mime-db',
          'semver',
          'lru-cache',
          'yallist',
          'lodash',
          /^lodash\//,
          'underscore',
          'uuid',
          'tough-cookie',
          'form-data',
          'combined-stream',
          'delayed-stream',
          'asynckit',
          'is-typedarray',
          'is-stream',
          'extend',
          'clone',
          'deep-extend',
          'qs',
          'safe-json-stringify',
          'json-stringify-safe',
          'caseless',
          'forever-agent',
          'tunnel-agent',
          'har-validator',
          'har-schema',
          'http-signature',
          'jsprim',
          'sshpk',
          'extsprintf',
          'json-schema',
          'verror',
          'core-util-is',
          'assert-plus',
          'bcrypt-pbkdf',
          'tweetnacl',
          'ecc-jsbn',
          'jsbn',
          'aws-sign2',
          'aws4',
          'bl',
          'brace-expansion',
          'balanced-match',
          'concat-map',
          'minimatch',
          'glob',
          'inflight',
          'inherits',
          'once',
          'path-is-absolute',
          'fs.realpath',
          'wrappy',
          'minimatch',
          'brace-expansion',
          'balanced-match',
          'concat-map'
        ],
        importType: 'module'
      }),
      // 排除有问题的大型依赖
      /^miniprogram-ci$/,
      /^express$/,
      /^ws$/,
      /^electron$/,
      /^@aws-sdk\//,
      /^babel-core$/,
      /^@babel\//,
      /^core-js-compat$/,
      /^terminal-kit$/,
      /^got$/,
      /^download$/,
      /^unzipper$/,
      // Node.js 内置模块
      /^node:/,
      /^fs$/,
      /^path$/,
      /^os$/,
      /^crypto$/,
      /^url$/,
      /^http$/,
      /^https$/,
      /^net$/,
      /^dns$/,
      /^zlib$/,
      /^fs\/promises$/,
      /^child_process$/,
      /^util$/,
      /^stream$/,
      /^events$/,
      /^buffer$/,
      /^process$/,
      /^querystring$/,
      /^string_decoder$/,
      /^timers$/,
      /^tty$/,
      /^vm$/,
      /^worker_threads$/,
      /^cluster$/,
      /^dgram$/,
      /^readline$/,
      /^repl$/,
      /^perf_hooks$/,
      /^inspector$/,
      /^async_hooks$/,
      /^trace_events$/,
      /^v8$/,
      /^constants$/,
      /^assert$/,
      /^module$/,
      /^domain$/,
      /^punycode$/
    ]
  },

  // 库文件 - CommonJS 版本，打包大部分依赖
  {
    ...baseConfig,
    name: 'library-cjs',
    entry: './src/index.ts',
    output: {
      path: path.resolve(__dirname, 'dist'),
      filename: 'index.cjs',
      library: {
        type: 'commonjs2'
      }
    },
    externals: [
      nodeExternals({
        // 打包大部分第三方依赖，但排除有问题的包
        allowlist: [
          'zod',
          'punycode', 
          '@types/adm-zip',
          'adm-zip',
          'cors',
          '@modelcontextprotocol/sdk',
          /^@modelcontextprotocol\/sdk\//,
          'zod-to-json-schema',
          'ajv',
          /^ajv\//,
          // 安全的第三方依赖
          'fast-json-stable-stringify',
          'open',
          'uri-js',
          'fast-deep-equal',
          'json-schema-traverse',
          // 小型工具库
          'is-wsl',
          'define-lazy-prop',
          'default-browser',
          'is-inside-container',
          'default-browser-id',
          'bundle-name', 
          'is-docker',
          'run-applescript',
          // CloudBase 包
          '@cloudbase/manager-node',
          /^@cloudbase\//,
          // 其他可以安全打包的依赖
          'tslib',
          'buffer',
          'process',
          'util',
          'events',
          'stream',
          'string_decoder',
          'querystring',
          'timers',
          'inherits',
          'safe-buffer',
          'readable-stream',
          'url',
          'core-util-is',
          'isarray',
          'util-deprecate',
          'string_decoder',
          'process-nextick-args',
          'end-of-stream',
          'once',
          'wrappy',
          'xtend',
          'minimist',
          'path-browserify',
          'os-browserify',
          'crypto-browserify',
          'browserify-zlib',
          'https-browserify',
          'http-browserify',
          'constants-browserify',
          'assert',
          'tty-browserify',
          'vm-browserify',
          'domain-browser',
          'console-browserify',
          'querystring-es3',
          'url-parse',
          'requires-port',
          'debug',
          'ms',
          'mime-types',
          'mime-db',
          'semver',
          'lru-cache',
          'yallist',
          'lodash',
          /^lodash\//,
          'underscore',
          'uuid',
          'tough-cookie',
          'form-data',
          'combined-stream',
          'delayed-stream',
          'asynckit',
          'is-typedarray',
          'is-stream',
          'extend',
          'clone',
          'deep-extend',
          'qs',
          'safe-json-stringify',
          'json-stringify-safe',
          'caseless',
          'forever-agent',
          'tunnel-agent',
          'har-validator',
          'har-schema',
          'http-signature',
          'jsprim',
          'sshpk',
          'extsprintf',
          'json-schema',
          'verror',
          'core-util-is',
          'assert-plus',
          'bcrypt-pbkdf',
          'tweetnacl',
          'ecc-jsbn',
          'jsbn',
          'aws-sign2',
          'aws4',
          'bl',
          'brace-expansion',
          'balanced-match',
          'concat-map',
          'minimatch',
          'glob',
          'inflight',
          'inherits',
          'once',
          'path-is-absolute',
          'fs.realpath',
          'wrappy',
          'minimatch',
          'brace-expansion',
          'balanced-match',
          'concat-map'
        ]
      }),
      // 排除有问题的大型依赖
      /^miniprogram-ci$/,
      /^express$/,
      /^ws$/,
      /^electron$/,
      /^@aws-sdk\//,
      /^babel-core$/,
      /^@babel\//,
      /^core-js-compat$/,
      /^terminal-kit$/,
      /^got$/,
      /^download$/,
      /^unzipper$/,
      // Node.js 内置模块
      /^node:/,
      /^fs$/,
      /^path$/,
      /^os$/,
      /^crypto$/,
      /^url$/,
      /^http$/,
      /^https$/,
      /^net$/,
      /^dns$/,
      /^zlib$/,
      /^fs\/promises$/,
      /^child_process$/,
      /^util$/,
      /^stream$/,
      /^events$/,
      /^buffer$/,
      /^process$/,
      /^querystring$/,
      /^string_decoder$/,
      /^timers$/,
      /^tty$/,
      /^vm$/,
      /^worker_threads$/,
      /^cluster$/,
      /^dgram$/,
      /^readline$/,
      /^repl$/,
      /^perf_hooks$/,
      /^inspector$/,
      /^async_hooks$/,
      /^trace_events$/,
      /^v8$/,
      /^constants$/,
      /^assert$/,
      /^module$/,
      /^domain$/,
      /^punycode$/
    ]
  },

  // CLI 全功能 bundle - ESM 版本，最大化依赖打包
  {
    ...baseConfig,
    name: 'cli-bundle-esm',
    entry: './src/cli.ts',
    output: {
      path: path.resolve(__dirname, 'dist'),
      filename: 'cli.js',
      library: {
        type: 'module'
      },
      chunkFormat: 'module',
      environment: {
        module: true,
        dynamicImport: true
      }
    },
    experiments: {
      outputModule: true
    },
    externalsType: 'module',
    externals: [
      nodeExternals({
        // 打包大部分第三方依赖，但排除有问题的包
        allowlist: [
          'zod',
          'punycode', 
          '@types/adm-zip',
          'adm-zip',
          'cors',
          '@modelcontextprotocol/sdk',
          /^@modelcontextprotocol\/sdk\//,
          'zod-to-json-schema',
          'ajv',
          /^ajv\//,
          // 安全的第三方依赖
          'fast-json-stable-stringify',
          'open',
          'uri-js',
          'fast-deep-equal',
          'json-schema-traverse',
          // 小型工具库
          'is-wsl',
          'define-lazy-prop',
          'default-browser',
          'is-inside-container',
          'default-browser-id',
          'bundle-name', 
          'is-docker',
          'run-applescript',
          // CloudBase 包
          '@cloudbase/manager-node',
          /^@cloudbase\//,
          // 其他可以安全打包的依赖
          'tslib',
          'buffer',
          'process',
          'util',
          'events',
          'stream',
          'string_decoder',
          'querystring',
          'timers',
          'inherits',
          'safe-buffer',
          'readable-stream',
          'url',
          'core-util-is',
          'isarray',
          'util-deprecate',
          'string_decoder',
          'process-nextick-args',
          'end-of-stream',
          'once',
          'wrappy',
          'xtend',
          'minimist',
          'path-browserify',
          'os-browserify',
          'crypto-browserify',
          'browserify-zlib',
          'https-browserify',
          'http-browserify',
          'constants-browserify',
          'assert',
          'tty-browserify',
          'vm-browserify',
          'domain-browser',
          'console-browserify',
          'querystring-es3',
          'url-parse',
          'requires-port',
          'debug',
          'ms',
          'mime-types',
          'mime-db',
          'semver',
          'lru-cache',
          'yallist',
          'lodash',
          /^lodash\//,
          'underscore',
          'uuid',
          'tough-cookie',
          'form-data',
          'combined-stream',
          'delayed-stream',
          'asynckit',
          'is-typedarray',
          'is-stream',
          'extend',
          'clone',
          'deep-extend',
          'qs',
          'safe-json-stringify',
          'json-stringify-safe',
          'caseless',
          'forever-agent',
          'tunnel-agent',
          'har-validator',
          'har-schema',
          'http-signature',
          'jsprim',
          'sshpk',
          'extsprintf',
          'json-schema',
          'verror',
          'core-util-is',
          'assert-plus',
          'bcrypt-pbkdf',
          'tweetnacl',
          'ecc-jsbn',
          'jsbn',
          'aws-sign2',
          'aws4',
          'bl',
          'brace-expansion',
          'balanced-match',
          'concat-map',
          'minimatch',
          'glob',
          'inflight',
          'inherits',
          'once',
          'path-is-absolute',
          'fs.realpath',
          'wrappy',
          'minimatch',
          'brace-expansion',
          'balanced-match',
          'concat-map'
        ],
        importType: 'module'
      }),
      // 排除有问题的大型依赖
      /^miniprogram-ci$/,
      /^express$/,
      /^ws$/,
      /^electron$/,
      /^@aws-sdk\//,
      /^babel-core$/,
      /^@babel\//,
      /^core-js-compat$/,
      /^terminal-kit$/,
      /^got$/,
      /^download$/,
      /^unzipper$/,
      // Node.js 内置模块
      /^node:/,
      /^fs$/,
      /^path$/,
      /^os$/,
      /^crypto$/,
      /^url$/,
      /^http$/,
      /^https$/,
      /^net$/,
      /^dns$/,
      /^zlib$/,
      /^fs\/promises$/,
      /^child_process$/,
      /^util$/,
      /^stream$/,
      /^events$/,
      /^buffer$/,
      /^process$/,
      /^querystring$/,
      /^string_decoder$/,
      /^timers$/,
      /^tty$/,
      /^vm$/,
      /^worker_threads$/,
      /^cluster$/,
      /^dgram$/,
      /^readline$/,
      /^repl$/,
      /^perf_hooks$/,
      /^inspector$/,
      /^async_hooks$/,
      /^trace_events$/,
      /^v8$/,
      /^constants$/,
      /^assert$/,
      /^module$/,
      /^domain$/,
      /^punycode$/
    ],
    plugins: [
      ...baseConfig.plugins,
      new webpack.BannerPlugin({
        banner: '#!/usr/bin/env node',
        raw: true,
        entryOnly: true
      })
    ]
  },

  // CLI 全功能 bundle - CommonJS 版本，最大化依赖打包
  {
    ...baseConfig,
    name: 'cli-bundle-cjs',
    entry: './src/cli.ts',
    output: {
      path: path.resolve(__dirname, 'dist'),
      filename: 'cli.cjs',
      library: {
        type: 'commonjs2'
      }
    },
    externals: [
      nodeExternals({
        // 打包大部分第三方依赖，但排除有问题的包
        allowlist: [
          'zod',
          'punycode', 
          '@types/adm-zip',
          'adm-zip',
          'cors',
          '@modelcontextprotocol/sdk',
          /^@modelcontextprotocol\/sdk\//,
          'zod-to-json-schema',
          'ajv',
          /^ajv\//,
          // 安全的第三方依赖
          'fast-json-stable-stringify',
          'open',
          'uri-js',
          'fast-deep-equal',
          'json-schema-traverse',
          // 小型工具库
          'is-wsl',
          'define-lazy-prop',
          'default-browser',
          'is-inside-container',
          'default-browser-id',
          'bundle-name', 
          'is-docker',
          'run-applescript',
          // CloudBase 包
          '@cloudbase/manager-node',
          /^@cloudbase\//,
          // 其他可以安全打包的依赖
          'tslib',
          'buffer',
          'process',
          'util',
          'events',
          'stream',
          'string_decoder',
          'querystring',
          'timers',
          'inherits',
          'safe-buffer',
          'readable-stream',
          'url',
          'core-util-is',
          'isarray',
          'util-deprecate',
          'string_decoder',
          'process-nextick-args',
          'end-of-stream',
          'once',
          'wrappy',
          'xtend',
          'minimist',
          'path-browserify',
          'os-browserify',
          'crypto-browserify',
          'browserify-zlib',
          'https-browserify',
          'http-browserify',
          'constants-browserify',
          'assert',
          'tty-browserify',
          'vm-browserify',
          'domain-browser',
          'console-browserify',
          'querystring-es3',
          'url-parse',
          'requires-port',
          'debug',
          'ms',
          'mime-types',
          'mime-db',
          'semver',
          'lru-cache',
          'yallist',
          'lodash',
          /^lodash\//,
          'underscore',
          'uuid',
          'tough-cookie',
          'form-data',
          'combined-stream',
          'delayed-stream',
          'asynckit',
          'is-typedarray',
          'is-stream',
          'extend',
          'clone',
          'deep-extend',
          'qs',
          'safe-json-stringify',
          'json-stringify-safe',
          'caseless',
          'forever-agent',
          'tunnel-agent',
          'har-validator',
          'har-schema',
          'http-signature',
          'jsprim',
          'sshpk',
          'extsprintf',
          'json-schema',
          'verror',
          'core-util-is',
          'assert-plus',
          'bcrypt-pbkdf',
          'tweetnacl',
          'ecc-jsbn',
          'jsbn',
          'aws-sign2',
          'aws4',
          'bl',
          'brace-expansion',
          'balanced-match',
          'concat-map',
          'minimatch',
          'glob',
          'inflight',
          'inherits',
          'once',
          'path-is-absolute',
          'fs.realpath',
          'wrappy',
          'minimatch',
          'brace-expansion',
          'balanced-match',
          'concat-map'
        ]
      }),
      // 排除有问题的大型依赖
      /^miniprogram-ci$/,
      /^express$/,
      /^ws$/,
      /^electron$/,
      /^@aws-sdk\//,
      /^babel-core$/,
      /^@babel\//,
      /^core-js-compat$/,
      /^terminal-kit$/,
      /^got$/,
      /^download$/,
      /^unzipper$/,
      // Node.js 内置模块
      /^node:/,
      /^fs$/,
      /^path$/,
      /^os$/,
      /^crypto$/,
      /^url$/,
      /^http$/,
      /^https$/,
      /^net$/,
      /^dns$/,
      /^zlib$/,
      /^fs\/promises$/,
      /^child_process$/,
      /^util$/,
      /^stream$/,
      /^events$/,
      /^buffer$/,
      /^process$/,
      /^querystring$/,
      /^string_decoder$/,
      /^timers$/,
      /^tty$/,
      /^vm$/,
      /^worker_threads$/,
      /^cluster$/,
      /^dgram$/,
      /^readline$/,
      /^repl$/,
      /^perf_hooks$/,
      /^inspector$/,
      /^async_hooks$/,
      /^trace_events$/,
      /^v8$/,
      /^constants$/,
      /^assert$/,
      /^module$/,
      /^domain$/,
      /^punycode$/
    ],
    plugins: [
      ...baseConfig.plugins,
      new webpack.BannerPlugin({
        banner: '#!/usr/bin/env node',
        raw: true,
        entryOnly: true
      })
    ]
  }
];